// GERADO AUTOMATICAMENTE — não edite à mão.
// Regenerar: node scripts/gen-rpg-items.mjs > src/game/rpgItems.gen.ts
export type Rarity = "common"|"uncommon"|"rare"|"epic"|"legendary"|"mythic"|"divine"|"ancestral"|"supreme";

export interface RpgItemTemplate {
  id: number;
  nameKey: string;
  slot: string;
  rarity: Rarity;
  minLevel: number;
  attack: number;
  defense: number;
  hp: number;
  speed: number;
  critical: number;
  icon: string;
  image: string;
  sellPrice: number;
}

export const RPG_ITEMS: RpgItemTemplate[] = [
  {
    "id": 1000,
    "nameKey": "item.rpg.espada_supreme_1",
    "slot": "weapon",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 125,
    "defense": 0,
    "hp": 32,
    "speed": 6,
    "critical": 20,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon1.png",
    "sellPrice": 900
  },
  {
    "id": 1001,
    "nameKey": "item.rpg.espada_ancestral_1",
    "slot": "weapon",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 95,
    "defense": 0,
    "hp": 29,
    "speed": 5,
    "critical": 17,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon2.png",
    "sellPrice": 780
  },
  {
    "id": 1002,
    "nameKey": "item.rpg.espada_divine_1",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 72,
    "defense": 0,
    "hp": 26,
    "speed": 4,
    "critical": 15,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon3.png",
    "sellPrice": 650
  },
  {
    "id": 1003,
    "nameKey": "item.rpg.espada_divine_2",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 74,
    "defense": 0,
    "hp": 28,
    "speed": 5,
    "critical": 17,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon4.png",
    "sellPrice": 650
  },
  {
    "id": 1004,
    "nameKey": "item.rpg.espada_mythic_1",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 52,
    "defense": 0,
    "hp": 23,
    "speed": 4,
    "critical": 13,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon5.png",
    "sellPrice": 500
  },
  {
    "id": 1005,
    "nameKey": "item.rpg.espada_legendary_1",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 36,
    "defense": 0,
    "hp": 20,
    "speed": 3,
    "critical": 11,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon6.png",
    "sellPrice": 350
  },
  {
    "id": 1006,
    "nameKey": "item.rpg.espada_legendary_2",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 38,
    "defense": 0,
    "hp": 22,
    "speed": 4,
    "critical": 12,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon8.png",
    "sellPrice": 350
  },
  {
    "id": 1007,
    "nameKey": "item.rpg.espada_epic_1",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 24,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon9.png",
    "sellPrice": 220
  },
  {
    "id": 1008,
    "nameKey": "item.rpg.espada_epic_2",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 26,
    "defense": 0,
    "hp": 19,
    "speed": 3,
    "critical": 10,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon10.png",
    "sellPrice": 220
  },
  {
    "id": 1009,
    "nameKey": "item.rpg.espada_epic_3",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 28,
    "defense": 0,
    "hp": 21,
    "speed": 2,
    "critical": 12,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon11.png",
    "sellPrice": 220
  },
  {
    "id": 1010,
    "nameKey": "item.rpg.espada_rare_1",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 16,
    "defense": 0,
    "hp": 14,
    "speed": 1,
    "critical": 6,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon12.png",
    "sellPrice": 120
  },
  {
    "id": 1011,
    "nameKey": "item.rpg.espada_rare_2",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 18,
    "defense": 0,
    "hp": 16,
    "speed": 2,
    "critical": 8,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon13.png",
    "sellPrice": 120
  },
  {
    "id": 1012,
    "nameKey": "item.rpg.espada_rare_3",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 20,
    "defense": 0,
    "hp": 18,
    "speed": 1,
    "critical": 9,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon14.png",
    "sellPrice": 120
  },
  {
    "id": 1013,
    "nameKey": "item.rpg.espada_uncommon_1",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 10,
    "defense": 0,
    "hp": 11,
    "speed": 1,
    "critical": 4,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon16.png",
    "sellPrice": 50
  },
  {
    "id": 1014,
    "nameKey": "item.rpg.espada_uncommon_2",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 12,
    "defense": 0,
    "hp": 13,
    "speed": 2,
    "critical": 6,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon17.png",
    "sellPrice": 50
  },
  {
    "id": 1015,
    "nameKey": "item.rpg.espada_uncommon_3",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 14,
    "defense": 0,
    "hp": 15,
    "speed": 1,
    "critical": 7,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon18.png",
    "sellPrice": 50
  },
  {
    "id": 1016,
    "nameKey": "item.rpg.espada_uncommon_4",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 16,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon19.png",
    "sellPrice": 50
  },
  {
    "id": 1017,
    "nameKey": "item.rpg.espada_common_1",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 6,
    "defense": 0,
    "hp": 8,
    "speed": 0,
    "critical": 2,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon20.png",
    "sellPrice": 10
  },
  {
    "id": 1018,
    "nameKey": "item.rpg.espada_common_2",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 8,
    "defense": 0,
    "hp": 10,
    "speed": 1,
    "critical": 4,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon275.png",
    "sellPrice": 10
  },
  {
    "id": 1019,
    "nameKey": "item.rpg.espada_common_3",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 10,
    "defense": 0,
    "hp": 12,
    "speed": 0,
    "critical": 5,
    "icon": "⚔️",
    "image": "/images/items/rpg/espada/Icon276.png",
    "sellPrice": 10
  },
  {
    "id": 1020,
    "nameKey": "item.rpg.machado_supreme_1",
    "slot": "weapon",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 125,
    "defense": 0,
    "hp": 32,
    "speed": 6,
    "critical": 20,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon41.png",
    "sellPrice": 900
  },
  {
    "id": 1021,
    "nameKey": "item.rpg.machado_ancestral_1",
    "slot": "weapon",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 95,
    "defense": 0,
    "hp": 29,
    "speed": 5,
    "critical": 17,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon42.png",
    "sellPrice": 780
  },
  {
    "id": 1022,
    "nameKey": "item.rpg.machado_divine_1",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 72,
    "defense": 0,
    "hp": 26,
    "speed": 4,
    "critical": 15,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon43.png",
    "sellPrice": 650
  },
  {
    "id": 1023,
    "nameKey": "item.rpg.machado_divine_2",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 74,
    "defense": 0,
    "hp": 28,
    "speed": 5,
    "critical": 17,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon44.png",
    "sellPrice": 650
  },
  {
    "id": 1024,
    "nameKey": "item.rpg.machado_mythic_1",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 52,
    "defense": 0,
    "hp": 23,
    "speed": 4,
    "critical": 13,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon45.png",
    "sellPrice": 500
  },
  {
    "id": 1025,
    "nameKey": "item.rpg.machado_mythic_2",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 54,
    "defense": 0,
    "hp": 25,
    "speed": 5,
    "critical": 15,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon46.png",
    "sellPrice": 500
  },
  {
    "id": 1026,
    "nameKey": "item.rpg.machado_legendary_1",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 36,
    "defense": 0,
    "hp": 20,
    "speed": 3,
    "critical": 11,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon47.png",
    "sellPrice": 350
  },
  {
    "id": 1027,
    "nameKey": "item.rpg.machado_legendary_2",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 38,
    "defense": 0,
    "hp": 22,
    "speed": 4,
    "critical": 12,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon48.png",
    "sellPrice": 350
  },
  {
    "id": 1028,
    "nameKey": "item.rpg.machado_legendary_3",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 40,
    "defense": 0,
    "hp": 24,
    "speed": 3,
    "critical": 14,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon49.png",
    "sellPrice": 350
  },
  {
    "id": 1029,
    "nameKey": "item.rpg.machado_epic_1",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 24,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon51.png",
    "sellPrice": 220
  },
  {
    "id": 1030,
    "nameKey": "item.rpg.machado_epic_2",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 26,
    "defense": 0,
    "hp": 19,
    "speed": 3,
    "critical": 10,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon52.png",
    "sellPrice": 220
  },
  {
    "id": 1031,
    "nameKey": "item.rpg.machado_rare_1",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 16,
    "defense": 0,
    "hp": 14,
    "speed": 1,
    "critical": 6,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon53.png",
    "sellPrice": 120
  },
  {
    "id": 1032,
    "nameKey": "item.rpg.machado_rare_2",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 18,
    "defense": 0,
    "hp": 16,
    "speed": 2,
    "critical": 8,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon54.png",
    "sellPrice": 120
  },
  {
    "id": 1033,
    "nameKey": "item.rpg.machado_rare_3",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 20,
    "defense": 0,
    "hp": 18,
    "speed": 1,
    "critical": 9,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon55.png",
    "sellPrice": 120
  },
  {
    "id": 1034,
    "nameKey": "item.rpg.machado_uncommon_1",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 10,
    "defense": 0,
    "hp": 11,
    "speed": 1,
    "critical": 4,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon57.png",
    "sellPrice": 50
  },
  {
    "id": 1035,
    "nameKey": "item.rpg.machado_uncommon_2",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 12,
    "defense": 0,
    "hp": 13,
    "speed": 2,
    "critical": 6,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon58.png",
    "sellPrice": 50
  },
  {
    "id": 1036,
    "nameKey": "item.rpg.machado_uncommon_3",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 14,
    "defense": 0,
    "hp": 15,
    "speed": 1,
    "critical": 7,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon59.png",
    "sellPrice": 50
  },
  {
    "id": 1037,
    "nameKey": "item.rpg.machado_common_1",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 6,
    "defense": 0,
    "hp": 8,
    "speed": 0,
    "critical": 2,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon60.png",
    "sellPrice": 10
  },
  {
    "id": 1038,
    "nameKey": "item.rpg.machado_common_2",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 8,
    "defense": 0,
    "hp": 10,
    "speed": 1,
    "critical": 4,
    "icon": "🪓",
    "image": "/images/items/rpg/machado/Icon76.png",
    "sellPrice": 10
  },
  {
    "id": 1039,
    "nameKey": "item.rpg.martelo_supreme_1",
    "slot": "weapon",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 125,
    "defense": 0,
    "hp": 32,
    "speed": 6,
    "critical": 20,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon21.png",
    "sellPrice": 900
  },
  {
    "id": 1040,
    "nameKey": "item.rpg.martelo_ancestral_1",
    "slot": "weapon",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 95,
    "defense": 0,
    "hp": 29,
    "speed": 5,
    "critical": 17,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon22.png",
    "sellPrice": 780
  },
  {
    "id": 1041,
    "nameKey": "item.rpg.martelo_divine_1",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 72,
    "defense": 0,
    "hp": 26,
    "speed": 4,
    "critical": 15,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon23.png",
    "sellPrice": 650
  },
  {
    "id": 1042,
    "nameKey": "item.rpg.martelo_divine_2",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 74,
    "defense": 0,
    "hp": 28,
    "speed": 5,
    "critical": 17,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon24.png",
    "sellPrice": 650
  },
  {
    "id": 1043,
    "nameKey": "item.rpg.martelo_mythic_1",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 52,
    "defense": 0,
    "hp": 23,
    "speed": 4,
    "critical": 13,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon25.png",
    "sellPrice": 500
  },
  {
    "id": 1044,
    "nameKey": "item.rpg.martelo_legendary_1",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 36,
    "defense": 0,
    "hp": 20,
    "speed": 3,
    "critical": 11,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon26.png",
    "sellPrice": 350
  },
  {
    "id": 1045,
    "nameKey": "item.rpg.martelo_legendary_2",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 38,
    "defense": 0,
    "hp": 22,
    "speed": 4,
    "critical": 12,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon27.png",
    "sellPrice": 350
  },
  {
    "id": 1046,
    "nameKey": "item.rpg.martelo_epic_1",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 24,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon28.png",
    "sellPrice": 220
  },
  {
    "id": 1047,
    "nameKey": "item.rpg.martelo_epic_2",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 26,
    "defense": 0,
    "hp": 19,
    "speed": 3,
    "critical": 10,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon29.png",
    "sellPrice": 220
  },
  {
    "id": 1048,
    "nameKey": "item.rpg.martelo_epic_3",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 28,
    "defense": 0,
    "hp": 21,
    "speed": 2,
    "critical": 12,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon30.png",
    "sellPrice": 220
  },
  {
    "id": 1049,
    "nameKey": "item.rpg.martelo_rare_1",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 16,
    "defense": 0,
    "hp": 14,
    "speed": 1,
    "critical": 6,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon31.png",
    "sellPrice": 120
  },
  {
    "id": 1050,
    "nameKey": "item.rpg.martelo_rare_2",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 18,
    "defense": 0,
    "hp": 16,
    "speed": 2,
    "critical": 8,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon32.png",
    "sellPrice": 120
  },
  {
    "id": 1051,
    "nameKey": "item.rpg.martelo_rare_3",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 20,
    "defense": 0,
    "hp": 18,
    "speed": 1,
    "critical": 9,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon33.png",
    "sellPrice": 120
  },
  {
    "id": 1052,
    "nameKey": "item.rpg.martelo_uncommon_1",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 10,
    "defense": 0,
    "hp": 11,
    "speed": 1,
    "critical": 4,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon34.png",
    "sellPrice": 50
  },
  {
    "id": 1053,
    "nameKey": "item.rpg.martelo_uncommon_2",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 12,
    "defense": 0,
    "hp": 13,
    "speed": 2,
    "critical": 6,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon35.png",
    "sellPrice": 50
  },
  {
    "id": 1054,
    "nameKey": "item.rpg.martelo_uncommon_3",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 14,
    "defense": 0,
    "hp": 15,
    "speed": 1,
    "critical": 7,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon36.png",
    "sellPrice": 50
  },
  {
    "id": 1055,
    "nameKey": "item.rpg.martelo_uncommon_4",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 16,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon37.png",
    "sellPrice": 50
  },
  {
    "id": 1056,
    "nameKey": "item.rpg.martelo_common_1",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 6,
    "defense": 0,
    "hp": 8,
    "speed": 0,
    "critical": 2,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon38.png",
    "sellPrice": 10
  },
  {
    "id": 1057,
    "nameKey": "item.rpg.martelo_common_2",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 8,
    "defense": 0,
    "hp": 10,
    "speed": 1,
    "critical": 4,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon39.png",
    "sellPrice": 10
  },
  {
    "id": 1058,
    "nameKey": "item.rpg.martelo_common_3",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 10,
    "defense": 0,
    "hp": 12,
    "speed": 0,
    "critical": 5,
    "icon": "🔨",
    "image": "/images/items/rpg/martelo/Icon40.png",
    "sellPrice": 10
  },
  {
    "id": 1059,
    "nameKey": "item.rpg.lanca_supreme_1",
    "slot": "weapon",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 125,
    "defense": 0,
    "hp": 32,
    "speed": 6,
    "critical": 20,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon7.png",
    "sellPrice": 900
  },
  {
    "id": 1060,
    "nameKey": "item.rpg.lanca_ancestral_1",
    "slot": "weapon",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 95,
    "defense": 0,
    "hp": 29,
    "speed": 5,
    "critical": 17,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon15.png",
    "sellPrice": 780
  },
  {
    "id": 1061,
    "nameKey": "item.rpg.lanca_divine_1",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 72,
    "defense": 0,
    "hp": 26,
    "speed": 4,
    "critical": 15,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon61.png",
    "sellPrice": 650
  },
  {
    "id": 1062,
    "nameKey": "item.rpg.lanca_divine_2",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 74,
    "defense": 0,
    "hp": 28,
    "speed": 5,
    "critical": 17,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon62.png",
    "sellPrice": 650
  },
  {
    "id": 1063,
    "nameKey": "item.rpg.lanca_mythic_1",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 52,
    "defense": 0,
    "hp": 23,
    "speed": 4,
    "critical": 13,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon64.png",
    "sellPrice": 500
  },
  {
    "id": 1064,
    "nameKey": "item.rpg.lanca_legendary_1",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 36,
    "defense": 0,
    "hp": 20,
    "speed": 3,
    "critical": 11,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon65.png",
    "sellPrice": 350
  },
  {
    "id": 1065,
    "nameKey": "item.rpg.lanca_legendary_2",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 38,
    "defense": 0,
    "hp": 22,
    "speed": 4,
    "critical": 12,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon66.png",
    "sellPrice": 350
  },
  {
    "id": 1066,
    "nameKey": "item.rpg.lanca_epic_1",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 24,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon67.png",
    "sellPrice": 220
  },
  {
    "id": 1067,
    "nameKey": "item.rpg.lanca_epic_2",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 26,
    "defense": 0,
    "hp": 19,
    "speed": 3,
    "critical": 10,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon68.png",
    "sellPrice": 220
  },
  {
    "id": 1068,
    "nameKey": "item.rpg.lanca_epic_3",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 28,
    "defense": 0,
    "hp": 21,
    "speed": 2,
    "critical": 12,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon69.png",
    "sellPrice": 220
  },
  {
    "id": 1069,
    "nameKey": "item.rpg.lanca_rare_1",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 16,
    "defense": 0,
    "hp": 14,
    "speed": 1,
    "critical": 6,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon70.png",
    "sellPrice": 120
  },
  {
    "id": 1070,
    "nameKey": "item.rpg.lanca_rare_2",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 18,
    "defense": 0,
    "hp": 16,
    "speed": 2,
    "critical": 8,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon71.png",
    "sellPrice": 120
  },
  {
    "id": 1071,
    "nameKey": "item.rpg.lanca_rare_3",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 20,
    "defense": 0,
    "hp": 18,
    "speed": 1,
    "critical": 9,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon72.png",
    "sellPrice": 120
  },
  {
    "id": 1072,
    "nameKey": "item.rpg.lanca_uncommon_1",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 10,
    "defense": 0,
    "hp": 11,
    "speed": 1,
    "critical": 4,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon73.png",
    "sellPrice": 50
  },
  {
    "id": 1073,
    "nameKey": "item.rpg.lanca_uncommon_2",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 12,
    "defense": 0,
    "hp": 13,
    "speed": 2,
    "critical": 6,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon74.png",
    "sellPrice": 50
  },
  {
    "id": 1074,
    "nameKey": "item.rpg.lanca_uncommon_3",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 14,
    "defense": 0,
    "hp": 15,
    "speed": 1,
    "critical": 7,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon75.png",
    "sellPrice": 50
  },
  {
    "id": 1075,
    "nameKey": "item.rpg.lanca_uncommon_4",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 16,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon77.png",
    "sellPrice": 50
  },
  {
    "id": 1076,
    "nameKey": "item.rpg.lanca_common_1",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 6,
    "defense": 0,
    "hp": 8,
    "speed": 0,
    "critical": 2,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon78.png",
    "sellPrice": 10
  },
  {
    "id": 1077,
    "nameKey": "item.rpg.lanca_common_2",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 8,
    "defense": 0,
    "hp": 10,
    "speed": 1,
    "critical": 4,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon79.png",
    "sellPrice": 10
  },
  {
    "id": 1078,
    "nameKey": "item.rpg.lanca_common_3",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 10,
    "defense": 0,
    "hp": 12,
    "speed": 0,
    "critical": 5,
    "icon": "🔱",
    "image": "/images/items/rpg/lanca/Icon80.png",
    "sellPrice": 10
  },
  {
    "id": 1079,
    "nameKey": "item.rpg.arco_supreme_1",
    "slot": "weapon",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 125,
    "defense": 0,
    "hp": 32,
    "speed": 6,
    "critical": 20,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon101.png",
    "sellPrice": 900
  },
  {
    "id": 1080,
    "nameKey": "item.rpg.arco_ancestral_1",
    "slot": "weapon",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 95,
    "defense": 0,
    "hp": 29,
    "speed": 5,
    "critical": 17,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon102.png",
    "sellPrice": 780
  },
  {
    "id": 1081,
    "nameKey": "item.rpg.arco_divine_1",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 72,
    "defense": 0,
    "hp": 26,
    "speed": 4,
    "critical": 15,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon103.png",
    "sellPrice": 650
  },
  {
    "id": 1082,
    "nameKey": "item.rpg.arco_divine_2",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 74,
    "defense": 0,
    "hp": 28,
    "speed": 5,
    "critical": 17,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon104.png",
    "sellPrice": 650
  },
  {
    "id": 1083,
    "nameKey": "item.rpg.arco_mythic_1",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 52,
    "defense": 0,
    "hp": 23,
    "speed": 4,
    "critical": 13,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon105.png",
    "sellPrice": 500
  },
  {
    "id": 1084,
    "nameKey": "item.rpg.arco_legendary_1",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 36,
    "defense": 0,
    "hp": 20,
    "speed": 3,
    "critical": 11,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon106.png",
    "sellPrice": 350
  },
  {
    "id": 1085,
    "nameKey": "item.rpg.arco_legendary_2",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 38,
    "defense": 0,
    "hp": 22,
    "speed": 4,
    "critical": 12,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon107.png",
    "sellPrice": 350
  },
  {
    "id": 1086,
    "nameKey": "item.rpg.arco_epic_1",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 24,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon108.png",
    "sellPrice": 220
  },
  {
    "id": 1087,
    "nameKey": "item.rpg.arco_epic_2",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 26,
    "defense": 0,
    "hp": 19,
    "speed": 3,
    "critical": 10,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon109.png",
    "sellPrice": 220
  },
  {
    "id": 1088,
    "nameKey": "item.rpg.arco_epic_3",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 28,
    "defense": 0,
    "hp": 21,
    "speed": 2,
    "critical": 12,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon110.png",
    "sellPrice": 220
  },
  {
    "id": 1089,
    "nameKey": "item.rpg.arco_rare_1",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 16,
    "defense": 0,
    "hp": 14,
    "speed": 1,
    "critical": 6,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon111.png",
    "sellPrice": 120
  },
  {
    "id": 1090,
    "nameKey": "item.rpg.arco_rare_2",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 18,
    "defense": 0,
    "hp": 16,
    "speed": 2,
    "critical": 8,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon112.png",
    "sellPrice": 120
  },
  {
    "id": 1091,
    "nameKey": "item.rpg.arco_rare_3",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 20,
    "defense": 0,
    "hp": 18,
    "speed": 1,
    "critical": 9,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon113.png",
    "sellPrice": 120
  },
  {
    "id": 1092,
    "nameKey": "item.rpg.arco_uncommon_1",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 10,
    "defense": 0,
    "hp": 11,
    "speed": 1,
    "critical": 4,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon114.png",
    "sellPrice": 50
  },
  {
    "id": 1093,
    "nameKey": "item.rpg.arco_uncommon_2",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 12,
    "defense": 0,
    "hp": 13,
    "speed": 2,
    "critical": 6,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon115.png",
    "sellPrice": 50
  },
  {
    "id": 1094,
    "nameKey": "item.rpg.arco_uncommon_3",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 14,
    "defense": 0,
    "hp": 15,
    "speed": 1,
    "critical": 7,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon116.png",
    "sellPrice": 50
  },
  {
    "id": 1095,
    "nameKey": "item.rpg.arco_uncommon_4",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 16,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon117.png",
    "sellPrice": 50
  },
  {
    "id": 1096,
    "nameKey": "item.rpg.arco_common_1",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 6,
    "defense": 0,
    "hp": 8,
    "speed": 0,
    "critical": 2,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon118.png",
    "sellPrice": 10
  },
  {
    "id": 1097,
    "nameKey": "item.rpg.arco_common_2",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 8,
    "defense": 0,
    "hp": 10,
    "speed": 1,
    "critical": 4,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon119.png",
    "sellPrice": 10
  },
  {
    "id": 1098,
    "nameKey": "item.rpg.arco_common_3",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 10,
    "defense": 0,
    "hp": 12,
    "speed": 0,
    "critical": 5,
    "icon": "🏹",
    "image": "/images/items/rpg/arco/Icon120.png",
    "sellPrice": 10
  },
  {
    "id": 1099,
    "nameKey": "item.rpg.crosbow_supreme_1",
    "slot": "weapon",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 125,
    "defense": 0,
    "hp": 32,
    "speed": 6,
    "critical": 20,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon121.png",
    "sellPrice": 900
  },
  {
    "id": 1100,
    "nameKey": "item.rpg.crosbow_ancestral_1",
    "slot": "weapon",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 95,
    "defense": 0,
    "hp": 29,
    "speed": 5,
    "critical": 17,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon122.png",
    "sellPrice": 780
  },
  {
    "id": 1101,
    "nameKey": "item.rpg.crosbow_divine_1",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 72,
    "defense": 0,
    "hp": 26,
    "speed": 4,
    "critical": 15,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon123.png",
    "sellPrice": 650
  },
  {
    "id": 1102,
    "nameKey": "item.rpg.crosbow_divine_2",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 74,
    "defense": 0,
    "hp": 28,
    "speed": 5,
    "critical": 17,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon124.png",
    "sellPrice": 650
  },
  {
    "id": 1103,
    "nameKey": "item.rpg.crosbow_mythic_1",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 52,
    "defense": 0,
    "hp": 23,
    "speed": 4,
    "critical": 13,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon125.png",
    "sellPrice": 500
  },
  {
    "id": 1104,
    "nameKey": "item.rpg.crosbow_legendary_1",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 36,
    "defense": 0,
    "hp": 20,
    "speed": 3,
    "critical": 11,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon126.png",
    "sellPrice": 350
  },
  {
    "id": 1105,
    "nameKey": "item.rpg.crosbow_legendary_2",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 38,
    "defense": 0,
    "hp": 22,
    "speed": 4,
    "critical": 12,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon127.png",
    "sellPrice": 350
  },
  {
    "id": 1106,
    "nameKey": "item.rpg.crosbow_epic_1",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 24,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon128.png",
    "sellPrice": 220
  },
  {
    "id": 1107,
    "nameKey": "item.rpg.crosbow_epic_2",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 26,
    "defense": 0,
    "hp": 19,
    "speed": 3,
    "critical": 10,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon129.png",
    "sellPrice": 220
  },
  {
    "id": 1108,
    "nameKey": "item.rpg.crosbow_epic_3",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 28,
    "defense": 0,
    "hp": 21,
    "speed": 2,
    "critical": 12,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon130.png",
    "sellPrice": 220
  },
  {
    "id": 1109,
    "nameKey": "item.rpg.crosbow_rare_1",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 16,
    "defense": 0,
    "hp": 14,
    "speed": 1,
    "critical": 6,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon131.png",
    "sellPrice": 120
  },
  {
    "id": 1110,
    "nameKey": "item.rpg.crosbow_rare_2",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 18,
    "defense": 0,
    "hp": 16,
    "speed": 2,
    "critical": 8,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon132.png",
    "sellPrice": 120
  },
  {
    "id": 1111,
    "nameKey": "item.rpg.crosbow_rare_3",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 20,
    "defense": 0,
    "hp": 18,
    "speed": 1,
    "critical": 9,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon133.png",
    "sellPrice": 120
  },
  {
    "id": 1112,
    "nameKey": "item.rpg.crosbow_uncommon_1",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 10,
    "defense": 0,
    "hp": 11,
    "speed": 1,
    "critical": 4,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon134.png",
    "sellPrice": 50
  },
  {
    "id": 1113,
    "nameKey": "item.rpg.crosbow_uncommon_2",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 12,
    "defense": 0,
    "hp": 13,
    "speed": 2,
    "critical": 6,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon135.png",
    "sellPrice": 50
  },
  {
    "id": 1114,
    "nameKey": "item.rpg.crosbow_uncommon_3",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 14,
    "defense": 0,
    "hp": 15,
    "speed": 1,
    "critical": 7,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon136.png",
    "sellPrice": 50
  },
  {
    "id": 1115,
    "nameKey": "item.rpg.crosbow_uncommon_4",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 16,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon137.png",
    "sellPrice": 50
  },
  {
    "id": 1116,
    "nameKey": "item.rpg.crosbow_common_1",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 6,
    "defense": 0,
    "hp": 8,
    "speed": 0,
    "critical": 2,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon138.png",
    "sellPrice": 10
  },
  {
    "id": 1117,
    "nameKey": "item.rpg.crosbow_common_2",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 8,
    "defense": 0,
    "hp": 10,
    "speed": 1,
    "critical": 4,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon139.png",
    "sellPrice": 10
  },
  {
    "id": 1118,
    "nameKey": "item.rpg.crosbow_common_3",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 10,
    "defense": 0,
    "hp": 12,
    "speed": 0,
    "critical": 5,
    "icon": "🎯",
    "image": "/images/items/rpg/crosbow/Icon140.png",
    "sellPrice": 10
  },
  {
    "id": 1119,
    "nameKey": "item.rpg.armaDupla_supreme_1",
    "slot": "weapon",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 125,
    "defense": 0,
    "hp": 32,
    "speed": 6,
    "critical": 20,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon89.png",
    "sellPrice": 900
  },
  {
    "id": 1120,
    "nameKey": "item.rpg.armaDupla_ancestral_1",
    "slot": "weapon",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 95,
    "defense": 0,
    "hp": 29,
    "speed": 5,
    "critical": 17,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon90.png",
    "sellPrice": 780
  },
  {
    "id": 1121,
    "nameKey": "item.rpg.armaDupla_divine_1",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 72,
    "defense": 0,
    "hp": 26,
    "speed": 4,
    "critical": 15,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon92.png",
    "sellPrice": 650
  },
  {
    "id": 1122,
    "nameKey": "item.rpg.armaDupla_mythic_1",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 52,
    "defense": 0,
    "hp": 23,
    "speed": 4,
    "critical": 13,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon93.png",
    "sellPrice": 500
  },
  {
    "id": 1123,
    "nameKey": "item.rpg.armaDupla_legendary_1",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 36,
    "defense": 0,
    "hp": 20,
    "speed": 3,
    "critical": 11,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon94.png",
    "sellPrice": 350
  },
  {
    "id": 1124,
    "nameKey": "item.rpg.armaDupla_legendary_2",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 38,
    "defense": 0,
    "hp": 22,
    "speed": 4,
    "critical": 12,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon95.png",
    "sellPrice": 350
  },
  {
    "id": 1125,
    "nameKey": "item.rpg.armaDupla_epic_1",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 24,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon96.png",
    "sellPrice": 220
  },
  {
    "id": 1126,
    "nameKey": "item.rpg.armaDupla_rare_1",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 16,
    "defense": 0,
    "hp": 14,
    "speed": 1,
    "critical": 6,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon97.png",
    "sellPrice": 120
  },
  {
    "id": 1127,
    "nameKey": "item.rpg.armaDupla_uncommon_1",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 10,
    "defense": 0,
    "hp": 11,
    "speed": 1,
    "critical": 4,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon98.png",
    "sellPrice": 50
  },
  {
    "id": 1128,
    "nameKey": "item.rpg.armaDupla_uncommon_2",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 12,
    "defense": 0,
    "hp": 13,
    "speed": 2,
    "critical": 6,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon99.png",
    "sellPrice": 50
  },
  {
    "id": 1129,
    "nameKey": "item.rpg.armaDupla_common_1",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 6,
    "defense": 0,
    "hp": 8,
    "speed": 0,
    "critical": 2,
    "icon": "⚔️",
    "image": "/images/items/rpg/arma-dupla/Icon100.png",
    "sellPrice": 10
  },
  {
    "id": 1130,
    "nameKey": "item.rpg.facas_supreme_1",
    "slot": "weapon",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 125,
    "defense": 0,
    "hp": 32,
    "speed": 6,
    "critical": 20,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon50.png",
    "sellPrice": 900
  },
  {
    "id": 1131,
    "nameKey": "item.rpg.facas_ancestral_1",
    "slot": "weapon",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 95,
    "defense": 0,
    "hp": 29,
    "speed": 5,
    "critical": 17,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon56.png",
    "sellPrice": 780
  },
  {
    "id": 1132,
    "nameKey": "item.rpg.facas_divine_1",
    "slot": "weapon",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 72,
    "defense": 0,
    "hp": 26,
    "speed": 4,
    "critical": 15,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon63.png",
    "sellPrice": 650
  },
  {
    "id": 1133,
    "nameKey": "item.rpg.facas_mythic_1",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 52,
    "defense": 0,
    "hp": 23,
    "speed": 4,
    "critical": 13,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon81.png",
    "sellPrice": 500
  },
  {
    "id": 1134,
    "nameKey": "item.rpg.facas_mythic_2",
    "slot": "weapon",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 54,
    "defense": 0,
    "hp": 25,
    "speed": 5,
    "critical": 15,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon82.png",
    "sellPrice": 500
  },
  {
    "id": 1135,
    "nameKey": "item.rpg.facas_legendary_1",
    "slot": "weapon",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 36,
    "defense": 0,
    "hp": 20,
    "speed": 3,
    "critical": 11,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon83.png",
    "sellPrice": 350
  },
  {
    "id": 1136,
    "nameKey": "item.rpg.facas_epic_1",
    "slot": "weapon",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 24,
    "defense": 0,
    "hp": 17,
    "speed": 2,
    "critical": 9,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon84.png",
    "sellPrice": 220
  },
  {
    "id": 1137,
    "nameKey": "item.rpg.facas_rare_1",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 16,
    "defense": 0,
    "hp": 14,
    "speed": 1,
    "critical": 6,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon85.png",
    "sellPrice": 120
  },
  {
    "id": 1138,
    "nameKey": "item.rpg.facas_rare_2",
    "slot": "weapon",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 18,
    "defense": 0,
    "hp": 16,
    "speed": 2,
    "critical": 8,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon86.png",
    "sellPrice": 120
  },
  {
    "id": 1139,
    "nameKey": "item.rpg.facas_uncommon_1",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 10,
    "defense": 0,
    "hp": 11,
    "speed": 1,
    "critical": 4,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon87.png",
    "sellPrice": 50
  },
  {
    "id": 1140,
    "nameKey": "item.rpg.facas_uncommon_2",
    "slot": "weapon",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 12,
    "defense": 0,
    "hp": 13,
    "speed": 2,
    "critical": 6,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon88.png",
    "sellPrice": 50
  },
  {
    "id": 1141,
    "nameKey": "item.rpg.facas_common_1",
    "slot": "weapon",
    "rarity": "common",
    "minLevel": 1,
    "attack": 6,
    "defense": 0,
    "hp": 8,
    "speed": 0,
    "critical": 2,
    "icon": "🗡️",
    "image": "/images/items/rpg/facas/Icon91.png",
    "sellPrice": 10
  },
  {
    "id": 1142,
    "nameKey": "item.rpg.escudo_supreme_1",
    "slot": "shield",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 0,
    "defense": 100,
    "hp": 94,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon141.png",
    "sellPrice": 900
  },
  {
    "id": 1143,
    "nameKey": "item.rpg.escudo_ancestral_1",
    "slot": "shield",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 0,
    "defense": 76,
    "hp": 86,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon142.png",
    "sellPrice": 780
  },
  {
    "id": 1144,
    "nameKey": "item.rpg.escudo_divine_1",
    "slot": "shield",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 0,
    "defense": 58,
    "hp": 78,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon143.png",
    "sellPrice": 650
  },
  {
    "id": 1145,
    "nameKey": "item.rpg.escudo_divine_2",
    "slot": "shield",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 0,
    "defense": 60,
    "hp": 82,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon144.png",
    "sellPrice": 650
  },
  {
    "id": 1146,
    "nameKey": "item.rpg.escudo_mythic_1",
    "slot": "shield",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 0,
    "defense": 42,
    "hp": 70,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon145.png",
    "sellPrice": 500
  },
  {
    "id": 1147,
    "nameKey": "item.rpg.escudo_legendary_1",
    "slot": "shield",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 0,
    "defense": 29,
    "hp": 62,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon146.png",
    "sellPrice": 350
  },
  {
    "id": 1148,
    "nameKey": "item.rpg.escudo_legendary_2",
    "slot": "shield",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 0,
    "defense": 31,
    "hp": 66,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon147.png",
    "sellPrice": 350
  },
  {
    "id": 1149,
    "nameKey": "item.rpg.escudo_epic_1",
    "slot": "shield",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 0,
    "defense": 19,
    "hp": 54,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon148.png",
    "sellPrice": 220
  },
  {
    "id": 1150,
    "nameKey": "item.rpg.escudo_epic_2",
    "slot": "shield",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 0,
    "defense": 21,
    "hp": 58,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon149.png",
    "sellPrice": 220
  },
  {
    "id": 1151,
    "nameKey": "item.rpg.escudo_epic_3",
    "slot": "shield",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 0,
    "defense": 23,
    "hp": 62,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon150.png",
    "sellPrice": 220
  },
  {
    "id": 1152,
    "nameKey": "item.rpg.escudo_rare_1",
    "slot": "shield",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 0,
    "defense": 13,
    "hp": 46,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon151.png",
    "sellPrice": 120
  },
  {
    "id": 1153,
    "nameKey": "item.rpg.escudo_rare_2",
    "slot": "shield",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 0,
    "defense": 15,
    "hp": 50,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon152.png",
    "sellPrice": 120
  },
  {
    "id": 1154,
    "nameKey": "item.rpg.escudo_rare_3",
    "slot": "shield",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 0,
    "defense": 17,
    "hp": 54,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon153.png",
    "sellPrice": 120
  },
  {
    "id": 1155,
    "nameKey": "item.rpg.escudo_uncommon_1",
    "slot": "shield",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 8,
    "hp": 38,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon154.png",
    "sellPrice": 50
  },
  {
    "id": 1156,
    "nameKey": "item.rpg.escudo_uncommon_2",
    "slot": "shield",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 10,
    "hp": 42,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon155.png",
    "sellPrice": 50
  },
  {
    "id": 1157,
    "nameKey": "item.rpg.escudo_uncommon_3",
    "slot": "shield",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 12,
    "hp": 46,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon156.png",
    "sellPrice": 50
  },
  {
    "id": 1158,
    "nameKey": "item.rpg.escudo_uncommon_4",
    "slot": "shield",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 14,
    "hp": 50,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon157.png",
    "sellPrice": 50
  },
  {
    "id": 1159,
    "nameKey": "item.rpg.escudo_common_1",
    "slot": "shield",
    "rarity": "common",
    "minLevel": 1,
    "attack": 0,
    "defense": 5,
    "hp": 30,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon158.png",
    "sellPrice": 10
  },
  {
    "id": 1160,
    "nameKey": "item.rpg.escudo_common_2",
    "slot": "shield",
    "rarity": "common",
    "minLevel": 1,
    "attack": 0,
    "defense": 7,
    "hp": 34,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon159.png",
    "sellPrice": 10
  },
  {
    "id": 1161,
    "nameKey": "item.rpg.escudo_common_3",
    "slot": "shield",
    "rarity": "common",
    "minLevel": 1,
    "attack": 0,
    "defense": 9,
    "hp": 38,
    "speed": 0,
    "critical": 0,
    "icon": "🛡️",
    "image": "/images/items/rpg/escudo/Icon160.png",
    "sellPrice": 10
  },
  {
    "id": 1162,
    "nameKey": "item.rpg.capacete_supreme_1",
    "slot": "helmet",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 0,
    "defense": 69,
    "hp": 72,
    "speed": 3,
    "critical": 7,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon161.png",
    "sellPrice": 900
  },
  {
    "id": 1163,
    "nameKey": "item.rpg.capacete_ancestral_1",
    "slot": "helmet",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 0,
    "defense": 52,
    "hp": 66,
    "speed": 3,
    "critical": 7,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon162.png",
    "sellPrice": 780
  },
  {
    "id": 1164,
    "nameKey": "item.rpg.capacete_divine_1",
    "slot": "helmet",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 0,
    "defense": 40,
    "hp": 60,
    "speed": 2,
    "critical": 6,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon163.png",
    "sellPrice": 650
  },
  {
    "id": 1165,
    "nameKey": "item.rpg.capacete_divine_2",
    "slot": "helmet",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 0,
    "defense": 42,
    "hp": 63,
    "speed": 2,
    "critical": 6,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon164.png",
    "sellPrice": 650
  },
  {
    "id": 1166,
    "nameKey": "item.rpg.capacete_mythic_1",
    "slot": "helmet",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 0,
    "defense": 29,
    "hp": 54,
    "speed": 2,
    "critical": 5,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon165.png",
    "sellPrice": 500
  },
  {
    "id": 1167,
    "nameKey": "item.rpg.capacete_mythic_2",
    "slot": "helmet",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 0,
    "defense": 31,
    "hp": 57,
    "speed": 2,
    "critical": 6,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon166.png",
    "sellPrice": 500
  },
  {
    "id": 1168,
    "nameKey": "item.rpg.capacete_legendary_1",
    "slot": "helmet",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 0,
    "defense": 20,
    "hp": 48,
    "speed": 2,
    "critical": 4,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon167.png",
    "sellPrice": 350
  },
  {
    "id": 1169,
    "nameKey": "item.rpg.capacete_legendary_2",
    "slot": "helmet",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 0,
    "defense": 22,
    "hp": 51,
    "speed": 2,
    "critical": 5,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon168.png",
    "sellPrice": 350
  },
  {
    "id": 1170,
    "nameKey": "item.rpg.capacete_epic_1",
    "slot": "helmet",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 0,
    "defense": 13,
    "hp": 42,
    "speed": 1,
    "critical": 3,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon169.png",
    "sellPrice": 220
  },
  {
    "id": 1171,
    "nameKey": "item.rpg.capacete_epic_2",
    "slot": "helmet",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 0,
    "defense": 15,
    "hp": 45,
    "speed": 1,
    "critical": 4,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon170.png",
    "sellPrice": 220
  },
  {
    "id": 1172,
    "nameKey": "item.rpg.capacete_epic_3",
    "slot": "helmet",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 0,
    "defense": 17,
    "hp": 48,
    "speed": 1,
    "critical": 4,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon171.png",
    "sellPrice": 220
  },
  {
    "id": 1173,
    "nameKey": "item.rpg.capacete_rare_1",
    "slot": "helmet",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 0,
    "defense": 9,
    "hp": 36,
    "speed": 1,
    "critical": 3,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon172.png",
    "sellPrice": 120
  },
  {
    "id": 1174,
    "nameKey": "item.rpg.capacete_rare_2",
    "slot": "helmet",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 0,
    "defense": 11,
    "hp": 39,
    "speed": 1,
    "critical": 3,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon173.png",
    "sellPrice": 120
  },
  {
    "id": 1175,
    "nameKey": "item.rpg.capacete_rare_3",
    "slot": "helmet",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 0,
    "defense": 13,
    "hp": 42,
    "speed": 1,
    "critical": 4,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon174.png",
    "sellPrice": 120
  },
  {
    "id": 1176,
    "nameKey": "item.rpg.capacete_uncommon_1",
    "slot": "helmet",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 6,
    "hp": 30,
    "speed": 0,
    "critical": 2,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon175.png",
    "sellPrice": 50
  },
  {
    "id": 1177,
    "nameKey": "item.rpg.capacete_uncommon_2",
    "slot": "helmet",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 8,
    "hp": 33,
    "speed": 0,
    "critical": 2,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon176.png",
    "sellPrice": 50
  },
  {
    "id": 1178,
    "nameKey": "item.rpg.capacete_uncommon_3",
    "slot": "helmet",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 10,
    "hp": 36,
    "speed": 0,
    "critical": 3,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon177.png",
    "sellPrice": 50
  },
  {
    "id": 1179,
    "nameKey": "item.rpg.capacete_uncommon_4",
    "slot": "helmet",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 12,
    "hp": 39,
    "speed": 0,
    "critical": 3,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon178.png",
    "sellPrice": 50
  },
  {
    "id": 1180,
    "nameKey": "item.rpg.capacete_common_1",
    "slot": "helmet",
    "rarity": "common",
    "minLevel": 1,
    "attack": 0,
    "defense": 3,
    "hp": 24,
    "speed": 0,
    "critical": 1,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon179.png",
    "sellPrice": 10
  },
  {
    "id": 1181,
    "nameKey": "item.rpg.capacete_common_2",
    "slot": "helmet",
    "rarity": "common",
    "minLevel": 1,
    "attack": 0,
    "defense": 5,
    "hp": 27,
    "speed": 0,
    "critical": 2,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon180.png",
    "sellPrice": 10
  },
  {
    "id": 1182,
    "nameKey": "item.rpg.capacete_common_3",
    "slot": "helmet",
    "rarity": "common",
    "minLevel": 1,
    "attack": 0,
    "defense": 7,
    "hp": 30,
    "speed": 0,
    "critical": 2,
    "icon": "⛑️",
    "image": "/images/items/rpg/capacete/Icon195.png",
    "sellPrice": 10
  },
  {
    "id": 1183,
    "nameKey": "item.rpg.peitoral_supreme_1",
    "slot": "armor",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 0,
    "defense": 113,
    "hp": 115,
    "speed": 2,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon181.png",
    "sellPrice": 900
  },
  {
    "id": 1184,
    "nameKey": "item.rpg.peitoral_ancestral_1",
    "slot": "armor",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 0,
    "defense": 86,
    "hp": 105,
    "speed": 2,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon182.png",
    "sellPrice": 780
  },
  {
    "id": 1185,
    "nameKey": "item.rpg.peitoral_divine_1",
    "slot": "armor",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 0,
    "defense": 65,
    "hp": 95,
    "speed": 2,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon183.png",
    "sellPrice": 650
  },
  {
    "id": 1186,
    "nameKey": "item.rpg.peitoral_divine_2",
    "slot": "armor",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 0,
    "defense": 67,
    "hp": 100,
    "speed": 2,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon184.png",
    "sellPrice": 650
  },
  {
    "id": 1187,
    "nameKey": "item.rpg.peitoral_mythic_1",
    "slot": "armor",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 0,
    "defense": 47,
    "hp": 85,
    "speed": 2,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon185.png",
    "sellPrice": 500
  },
  {
    "id": 1188,
    "nameKey": "item.rpg.peitoral_mythic_2",
    "slot": "armor",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 0,
    "defense": 49,
    "hp": 90,
    "speed": 2,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon186.png",
    "sellPrice": 500
  },
  {
    "id": 1189,
    "nameKey": "item.rpg.peitoral_legendary_1",
    "slot": "armor",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 0,
    "defense": 32,
    "hp": 75,
    "speed": 1,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon187.png",
    "sellPrice": 350
  },
  {
    "id": 1190,
    "nameKey": "item.rpg.peitoral_legendary_2",
    "slot": "armor",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 0,
    "defense": 34,
    "hp": 80,
    "speed": 1,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon188.png",
    "sellPrice": 350
  },
  {
    "id": 1191,
    "nameKey": "item.rpg.peitoral_legendary_3",
    "slot": "armor",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 0,
    "defense": 36,
    "hp": 85,
    "speed": 1,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon189.png",
    "sellPrice": 350
  },
  {
    "id": 1192,
    "nameKey": "item.rpg.peitoral_epic_1",
    "slot": "armor",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 0,
    "defense": 22,
    "hp": 65,
    "speed": 1,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon190.png",
    "sellPrice": 220
  },
  {
    "id": 1193,
    "nameKey": "item.rpg.peitoral_epic_2",
    "slot": "armor",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 0,
    "defense": 24,
    "hp": 70,
    "speed": 1,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon191.png",
    "sellPrice": 220
  },
  {
    "id": 1194,
    "nameKey": "item.rpg.peitoral_rare_1",
    "slot": "armor",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 0,
    "defense": 14,
    "hp": 55,
    "speed": 1,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon192.png",
    "sellPrice": 120
  },
  {
    "id": 1195,
    "nameKey": "item.rpg.peitoral_rare_2",
    "slot": "armor",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 0,
    "defense": 16,
    "hp": 60,
    "speed": 1,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon193.png",
    "sellPrice": 120
  },
  {
    "id": 1196,
    "nameKey": "item.rpg.peitoral_rare_3",
    "slot": "armor",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 0,
    "defense": 18,
    "hp": 65,
    "speed": 1,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon194.png",
    "sellPrice": 120
  },
  {
    "id": 1197,
    "nameKey": "item.rpg.peitoral_uncommon_1",
    "slot": "armor",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 9,
    "hp": 45,
    "speed": 0,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon196.png",
    "sellPrice": 50
  },
  {
    "id": 1198,
    "nameKey": "item.rpg.peitoral_uncommon_2",
    "slot": "armor",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 11,
    "hp": 50,
    "speed": 0,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon197.png",
    "sellPrice": 50
  },
  {
    "id": 1199,
    "nameKey": "item.rpg.peitoral_uncommon_3",
    "slot": "armor",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 0,
    "defense": 13,
    "hp": 55,
    "speed": 0,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon198.png",
    "sellPrice": 50
  },
  {
    "id": 1200,
    "nameKey": "item.rpg.peitoral_common_1",
    "slot": "armor",
    "rarity": "common",
    "minLevel": 1,
    "attack": 0,
    "defense": 5,
    "hp": 35,
    "speed": 0,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon199.png",
    "sellPrice": 10
  },
  {
    "id": 1201,
    "nameKey": "item.rpg.peitoral_common_2",
    "slot": "armor",
    "rarity": "common",
    "minLevel": 1,
    "attack": 0,
    "defense": 7,
    "hp": 40,
    "speed": 0,
    "critical": 0,
    "icon": "🦺",
    "image": "/images/items/rpg/peitoral/Icon200.png",
    "sellPrice": 10
  },
  {
    "id": 1202,
    "nameKey": "item.rpg.luvas_supreme_1",
    "slot": "gloves",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 44,
    "defense": 56,
    "hp": 47,
    "speed": 6,
    "critical": 11,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon201.png",
    "sellPrice": 900
  },
  {
    "id": 1203,
    "nameKey": "item.rpg.luvas_ancestral_1",
    "slot": "gloves",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 33,
    "defense": 43,
    "hp": 43,
    "speed": 5,
    "critical": 9,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon202.png",
    "sellPrice": 780
  },
  {
    "id": 1204,
    "nameKey": "item.rpg.luvas_divine_1",
    "slot": "gloves",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 25,
    "defense": 32,
    "hp": 39,
    "speed": 5,
    "critical": 8,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon203.png",
    "sellPrice": 650
  },
  {
    "id": 1205,
    "nameKey": "item.rpg.luvas_divine_2",
    "slot": "gloves",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 26,
    "defense": 34,
    "hp": 41,
    "speed": 6,
    "critical": 9,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon204.png",
    "sellPrice": 650
  },
  {
    "id": 1206,
    "nameKey": "item.rpg.luvas_mythic_1",
    "slot": "gloves",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 18,
    "defense": 23,
    "hp": 35,
    "speed": 4,
    "critical": 7,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon205.png",
    "sellPrice": 500
  },
  {
    "id": 1207,
    "nameKey": "item.rpg.luvas_legendary_1",
    "slot": "gloves",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 13,
    "defense": 16,
    "hp": 31,
    "speed": 3,
    "critical": 6,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon206.png",
    "sellPrice": 350
  },
  {
    "id": 1208,
    "nameKey": "item.rpg.luvas_legendary_2",
    "slot": "gloves",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 14,
    "defense": 18,
    "hp": 33,
    "speed": 4,
    "critical": 7,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon207.png",
    "sellPrice": 350
  },
  {
    "id": 1209,
    "nameKey": "item.rpg.luvas_epic_1",
    "slot": "gloves",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 8,
    "defense": 11,
    "hp": 27,
    "speed": 3,
    "critical": 5,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon208.png",
    "sellPrice": 220
  },
  {
    "id": 1210,
    "nameKey": "item.rpg.luvas_epic_2",
    "slot": "gloves",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 9,
    "defense": 13,
    "hp": 29,
    "speed": 4,
    "critical": 5,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon209.png",
    "sellPrice": 220
  },
  {
    "id": 1211,
    "nameKey": "item.rpg.luvas_epic_3",
    "slot": "gloves",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 10,
    "defense": 15,
    "hp": 31,
    "speed": 3,
    "critical": 6,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon210.png",
    "sellPrice": 220
  },
  {
    "id": 1212,
    "nameKey": "item.rpg.luvas_rare_1",
    "slot": "gloves",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 6,
    "defense": 7,
    "hp": 23,
    "speed": 2,
    "critical": 3,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon211.png",
    "sellPrice": 120
  },
  {
    "id": 1213,
    "nameKey": "item.rpg.luvas_rare_2",
    "slot": "gloves",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 7,
    "defense": 9,
    "hp": 25,
    "speed": 3,
    "critical": 4,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon212.png",
    "sellPrice": 120
  },
  {
    "id": 1214,
    "nameKey": "item.rpg.luvas_rare_3",
    "slot": "gloves",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 8,
    "defense": 11,
    "hp": 27,
    "speed": 2,
    "critical": 5,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon213.png",
    "sellPrice": 120
  },
  {
    "id": 1215,
    "nameKey": "item.rpg.luvas_uncommon_1",
    "slot": "gloves",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 4,
    "defense": 5,
    "hp": 19,
    "speed": 2,
    "critical": 2,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon214.png",
    "sellPrice": 50
  },
  {
    "id": 1216,
    "nameKey": "item.rpg.luvas_uncommon_2",
    "slot": "gloves",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 5,
    "defense": 7,
    "hp": 21,
    "speed": 3,
    "critical": 3,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon215.png",
    "sellPrice": 50
  },
  {
    "id": 1217,
    "nameKey": "item.rpg.luvas_uncommon_3",
    "slot": "gloves",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 6,
    "defense": 9,
    "hp": 23,
    "speed": 2,
    "critical": 4,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon216.png",
    "sellPrice": 50
  },
  {
    "id": 1218,
    "nameKey": "item.rpg.luvas_uncommon_4",
    "slot": "gloves",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 7,
    "defense": 11,
    "hp": 25,
    "speed": 3,
    "critical": 5,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon217.png",
    "sellPrice": 50
  },
  {
    "id": 1219,
    "nameKey": "item.rpg.luvas_common_1",
    "slot": "gloves",
    "rarity": "common",
    "minLevel": 1,
    "attack": 2,
    "defense": 3,
    "hp": 15,
    "speed": 1,
    "critical": 1,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon218.png",
    "sellPrice": 10
  },
  {
    "id": 1220,
    "nameKey": "item.rpg.luvas_common_2",
    "slot": "gloves",
    "rarity": "common",
    "minLevel": 1,
    "attack": 3,
    "defense": 5,
    "hp": 17,
    "speed": 2,
    "critical": 2,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon219.png",
    "sellPrice": 10
  },
  {
    "id": 1221,
    "nameKey": "item.rpg.luvas_common_3",
    "slot": "gloves",
    "rarity": "common",
    "minLevel": 1,
    "attack": 4,
    "defense": 7,
    "hp": 19,
    "speed": 1,
    "critical": 3,
    "icon": "🧤",
    "image": "/images/items/rpg/luvas/Icon220.png",
    "sellPrice": 10
  },
  {
    "id": 1222,
    "nameKey": "item.rpg.sapatos_supreme_1",
    "slot": "boots",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 19,
    "defense": 44,
    "hp": 58,
    "speed": 12,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon221.png",
    "sellPrice": 900
  },
  {
    "id": 1223,
    "nameKey": "item.rpg.sapatos_ancestral_1",
    "slot": "boots",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 14,
    "defense": 33,
    "hp": 53,
    "speed": 10,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon222.png",
    "sellPrice": 780
  },
  {
    "id": 1224,
    "nameKey": "item.rpg.sapatos_divine_1",
    "slot": "boots",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 11,
    "defense": 25,
    "hp": 48,
    "speed": 9,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon223.png",
    "sellPrice": 650
  },
  {
    "id": 1225,
    "nameKey": "item.rpg.sapatos_divine_2",
    "slot": "boots",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 11,
    "defense": 27,
    "hp": 51,
    "speed": 10,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon224.png",
    "sellPrice": 650
  },
  {
    "id": 1226,
    "nameKey": "item.rpg.sapatos_mythic_1",
    "slot": "boots",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 8,
    "defense": 18,
    "hp": 43,
    "speed": 8,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon225.png",
    "sellPrice": 500
  },
  {
    "id": 1227,
    "nameKey": "item.rpg.sapatos_legendary_1",
    "slot": "boots",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 5,
    "defense": 13,
    "hp": 38,
    "speed": 7,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon226.png",
    "sellPrice": 350
  },
  {
    "id": 1228,
    "nameKey": "item.rpg.sapatos_legendary_2",
    "slot": "boots",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 5,
    "defense": 15,
    "hp": 41,
    "speed": 8,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon227.png",
    "sellPrice": 350
  },
  {
    "id": 1229,
    "nameKey": "item.rpg.sapatos_epic_1",
    "slot": "boots",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 4,
    "defense": 8,
    "hp": 33,
    "speed": 6,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon228.png",
    "sellPrice": 220
  },
  {
    "id": 1230,
    "nameKey": "item.rpg.sapatos_epic_2",
    "slot": "boots",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 4,
    "defense": 10,
    "hp": 36,
    "speed": 7,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon229.png",
    "sellPrice": 220
  },
  {
    "id": 1231,
    "nameKey": "item.rpg.sapatos_epic_3",
    "slot": "boots",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 4,
    "defense": 12,
    "hp": 39,
    "speed": 8,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon230.png",
    "sellPrice": 220
  },
  {
    "id": 1232,
    "nameKey": "item.rpg.sapatos_rare_1",
    "slot": "boots",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 2,
    "defense": 6,
    "hp": 28,
    "speed": 4,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon231.png",
    "sellPrice": 120
  },
  {
    "id": 1233,
    "nameKey": "item.rpg.sapatos_rare_2",
    "slot": "boots",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 2,
    "defense": 8,
    "hp": 31,
    "speed": 5,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon232.png",
    "sellPrice": 120
  },
  {
    "id": 1234,
    "nameKey": "item.rpg.sapatos_rare_3",
    "slot": "boots",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 2,
    "defense": 10,
    "hp": 34,
    "speed": 6,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon233.png",
    "sellPrice": 120
  },
  {
    "id": 1235,
    "nameKey": "item.rpg.sapatos_uncommon_1",
    "slot": "boots",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 2,
    "defense": 4,
    "hp": 23,
    "speed": 3,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon234.png",
    "sellPrice": 50
  },
  {
    "id": 1236,
    "nameKey": "item.rpg.sapatos_uncommon_2",
    "slot": "boots",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 2,
    "defense": 6,
    "hp": 26,
    "speed": 4,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon235.png",
    "sellPrice": 50
  },
  {
    "id": 1237,
    "nameKey": "item.rpg.sapatos_uncommon_3",
    "slot": "boots",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 2,
    "defense": 8,
    "hp": 29,
    "speed": 5,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon236.png",
    "sellPrice": 50
  },
  {
    "id": 1238,
    "nameKey": "item.rpg.sapatos_uncommon_4",
    "slot": "boots",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 2,
    "defense": 10,
    "hp": 32,
    "speed": 6,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon237.png",
    "sellPrice": 50
  },
  {
    "id": 1239,
    "nameKey": "item.rpg.sapatos_common_1",
    "slot": "boots",
    "rarity": "common",
    "minLevel": 1,
    "attack": 1,
    "defense": 2,
    "hp": 18,
    "speed": 2,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon238.png",
    "sellPrice": 10
  },
  {
    "id": 1240,
    "nameKey": "item.rpg.sapatos_common_2",
    "slot": "boots",
    "rarity": "common",
    "minLevel": 1,
    "attack": 1,
    "defense": 4,
    "hp": 21,
    "speed": 3,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon239.png",
    "sellPrice": 10
  },
  {
    "id": 1241,
    "nameKey": "item.rpg.sapatos_common_3",
    "slot": "boots",
    "rarity": "common",
    "minLevel": 1,
    "attack": 1,
    "defense": 6,
    "hp": 24,
    "speed": 4,
    "critical": 0,
    "icon": "👢",
    "image": "/images/items/rpg/sapatos/Icon240.png",
    "sellPrice": 10
  },
  {
    "id": 1242,
    "nameKey": "item.rpg.anel_supreme_1",
    "slot": "ring",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 38,
    "defense": 25,
    "hp": 60,
    "speed": 5,
    "critical": 10,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon241.png",
    "sellPrice": 900
  },
  {
    "id": 1243,
    "nameKey": "item.rpg.anel_ancestral_1",
    "slot": "ring",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 29,
    "defense": 19,
    "hp": 55,
    "speed": 5,
    "critical": 9,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon242.png",
    "sellPrice": 780
  },
  {
    "id": 1244,
    "nameKey": "item.rpg.anel_divine_1",
    "slot": "ring",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 22,
    "defense": 14,
    "hp": 50,
    "speed": 4,
    "critical": 8,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon243.png",
    "sellPrice": 650
  },
  {
    "id": 1245,
    "nameKey": "item.rpg.anel_mythic_1",
    "slot": "ring",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 16,
    "defense": 10,
    "hp": 45,
    "speed": 4,
    "critical": 7,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon244.png",
    "sellPrice": 500
  },
  {
    "id": 1246,
    "nameKey": "item.rpg.anel_legendary_1",
    "slot": "ring",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 11,
    "defense": 7,
    "hp": 40,
    "speed": 3,
    "critical": 5,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon245.png",
    "sellPrice": 350
  },
  {
    "id": 1247,
    "nameKey": "item.rpg.anel_epic_1",
    "slot": "ring",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 7,
    "defense": 5,
    "hp": 35,
    "speed": 3,
    "critical": 4,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon246.png",
    "sellPrice": 220
  },
  {
    "id": 1248,
    "nameKey": "item.rpg.anel_rare_1",
    "slot": "ring",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 5,
    "defense": 3,
    "hp": 30,
    "speed": 2,
    "critical": 3,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon247.png",
    "sellPrice": 120
  },
  {
    "id": 1249,
    "nameKey": "item.rpg.anel_uncommon_1",
    "slot": "ring",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 3,
    "defense": 2,
    "hp": 25,
    "speed": 2,
    "critical": 2,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon248.png",
    "sellPrice": 50
  },
  {
    "id": 1250,
    "nameKey": "item.rpg.anel_uncommon_2",
    "slot": "ring",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 4,
    "defense": 2,
    "hp": 27,
    "speed": 2,
    "critical": 3,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon249.png",
    "sellPrice": 50
  },
  {
    "id": 1251,
    "nameKey": "item.rpg.anel_common_1",
    "slot": "ring",
    "rarity": "common",
    "minLevel": 1,
    "attack": 2,
    "defense": 1,
    "hp": 20,
    "speed": 1,
    "critical": 1,
    "icon": "💍",
    "image": "/images/items/rpg/anel/Icon250.png",
    "sellPrice": 10
  },
  {
    "id": 1252,
    "nameKey": "item.rpg.colar_supreme_1",
    "slot": "amulet",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 35,
    "defense": 28,
    "hp": 74,
    "speed": 3,
    "critical": 8,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon251.png",
    "sellPrice": 900
  },
  {
    "id": 1253,
    "nameKey": "item.rpg.colar_ancestral_1",
    "slot": "amulet",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 27,
    "defense": 21,
    "hp": 68,
    "speed": 3,
    "critical": 7,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon252.png",
    "sellPrice": 780
  },
  {
    "id": 1254,
    "nameKey": "item.rpg.colar_divine_1",
    "slot": "amulet",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 20,
    "defense": 16,
    "hp": 62,
    "speed": 2,
    "critical": 6,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon253.png",
    "sellPrice": 650
  },
  {
    "id": 1255,
    "nameKey": "item.rpg.colar_mythic_1",
    "slot": "amulet",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 15,
    "defense": 11,
    "hp": 56,
    "speed": 2,
    "critical": 6,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon254.png",
    "sellPrice": 500
  },
  {
    "id": 1256,
    "nameKey": "item.rpg.colar_legendary_1",
    "slot": "amulet",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 10,
    "defense": 8,
    "hp": 50,
    "speed": 2,
    "critical": 5,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon255.png",
    "sellPrice": 350
  },
  {
    "id": 1257,
    "nameKey": "item.rpg.colar_epic_1",
    "slot": "amulet",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 7,
    "defense": 5,
    "hp": 44,
    "speed": 1,
    "critical": 4,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon256.png",
    "sellPrice": 220
  },
  {
    "id": 1258,
    "nameKey": "item.rpg.colar_rare_1",
    "slot": "amulet",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 4,
    "defense": 4,
    "hp": 38,
    "speed": 1,
    "critical": 3,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon257.png",
    "sellPrice": 120
  },
  {
    "id": 1259,
    "nameKey": "item.rpg.colar_uncommon_1",
    "slot": "amulet",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 3,
    "defense": 2,
    "hp": 32,
    "speed": 0,
    "critical": 2,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon258.png",
    "sellPrice": 50
  },
  {
    "id": 1260,
    "nameKey": "item.rpg.colar_uncommon_2",
    "slot": "amulet",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 4,
    "defense": 2,
    "hp": 35,
    "speed": 0,
    "critical": 2,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon259.png",
    "sellPrice": 50
  },
  {
    "id": 1261,
    "nameKey": "item.rpg.colar_common_1",
    "slot": "amulet",
    "rarity": "common",
    "minLevel": 1,
    "attack": 2,
    "defense": 1,
    "hp": 26,
    "speed": 0,
    "critical": 1,
    "icon": "📿",
    "image": "/images/items/rpg/colar/Icon260.png",
    "sellPrice": 10
  },
  {
    "id": 1262,
    "nameKey": "item.rpg.emblema_supreme_1",
    "slot": "relic",
    "rarity": "supreme",
    "minLevel": 90,
    "attack": 50,
    "defense": 31,
    "hp": 56,
    "speed": 7,
    "critical": 11,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon261.png",
    "sellPrice": 900
  },
  {
    "id": 1263,
    "nameKey": "item.rpg.emblema_ancestral_1",
    "slot": "relic",
    "rarity": "ancestral",
    "minLevel": 78,
    "attack": 38,
    "defense": 24,
    "hp": 51,
    "speed": 6,
    "critical": 10,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon262.png",
    "sellPrice": 780
  },
  {
    "id": 1264,
    "nameKey": "item.rpg.emblema_divine_1",
    "slot": "relic",
    "rarity": "divine",
    "minLevel": 65,
    "attack": 29,
    "defense": 18,
    "hp": 46,
    "speed": 5,
    "critical": 9,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon263.png",
    "sellPrice": 650
  },
  {
    "id": 1265,
    "nameKey": "item.rpg.emblema_mythic_1",
    "slot": "relic",
    "rarity": "mythic",
    "minLevel": 50,
    "attack": 21,
    "defense": 13,
    "hp": 41,
    "speed": 5,
    "critical": 8,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon264.png",
    "sellPrice": 500
  },
  {
    "id": 1266,
    "nameKey": "item.rpg.emblema_legendary_1",
    "slot": "relic",
    "rarity": "legendary",
    "minLevel": 35,
    "attack": 14,
    "defense": 9,
    "hp": 36,
    "speed": 4,
    "critical": 6,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon265.png",
    "sellPrice": 350
  },
  {
    "id": 1267,
    "nameKey": "item.rpg.emblema_epic_1",
    "slot": "relic",
    "rarity": "epic",
    "minLevel": 22,
    "attack": 10,
    "defense": 6,
    "hp": 31,
    "speed": 3,
    "critical": 5,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon266.png",
    "sellPrice": 220
  },
  {
    "id": 1268,
    "nameKey": "item.rpg.emblema_rare_1",
    "slot": "relic",
    "rarity": "rare",
    "minLevel": 12,
    "attack": 6,
    "defense": 4,
    "hp": 26,
    "speed": 2,
    "critical": 4,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon267.png",
    "sellPrice": 120
  },
  {
    "id": 1269,
    "nameKey": "item.rpg.emblema_uncommon_1",
    "slot": "relic",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 4,
    "defense": 3,
    "hp": 21,
    "speed": 2,
    "critical": 2,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon268.png",
    "sellPrice": 50
  },
  {
    "id": 1270,
    "nameKey": "item.rpg.emblema_uncommon_2",
    "slot": "relic",
    "rarity": "uncommon",
    "minLevel": 5,
    "attack": 5,
    "defense": 3,
    "hp": 23,
    "speed": 2,
    "critical": 3,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon269.png",
    "sellPrice": 50
  },
  {
    "id": 1271,
    "nameKey": "item.rpg.emblema_common_1",
    "slot": "relic",
    "rarity": "common",
    "minLevel": 1,
    "attack": 2,
    "defense": 2,
    "hp": 16,
    "speed": 1,
    "critical": 1,
    "icon": "🔮",
    "image": "/images/items/rpg/emblema/Icon270.png",
    "sellPrice": 10
  }
];
